Crm\GeneralBundle\Entity\Estado:
    type: entity
    table: null
    repositoryClass: Crm\GeneralBundle\Entity\EstadoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreEstado:
            type: string
            length: '50'
            column: nombre_estado
    oneToMany:
        municipio:
           targetEntity: Crm\GeneralBundle\Entity\Municipio
           mappedBy: Estado
        direccionCliente:
           targetEntity: Crm\ClienteBundle\Entity\DireccionCliente
           mappedBy: Estado
        direccionEmpresa:
           targetEntity: Crm\EmpresaBundle\Entity\DireccionEmpresa
           mappedBy: Estado
        direccionFabricante:
           targetEntity: Crm\FabricanteBundle\Entity\DireccionFabricante
           mappedBy: Estado
        ubicacion:
           targetEntity: Crm\EquipoBundle\Entity\Ubicacion
           mappedBy: Estado
        direccionPersonal:
           targetEntity: Crm\PersonalBundle\Entity\DireccionPersonal
           mappedBy: Estado
    manyToOne:
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: estado
          joinColumn: 
               name: pais_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
