Crm\GeneralBundle\Entity\Localidad:
    type: entity
    table: null
    repositoryClass: Crm\GeneralBundle\Entity\LocalidadRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreLocalidad:
            type: string
            length: '50'
            column: nombre_localidad
    manyToOne:
        estado:
          targetEntity: Crm\GeneralBundle\Entity\Estado
          inversedBy: localidad
          joinColumn:
               name: estado_id
               referencedColumnName: id
    oneToMany:
        direccionCliente:
           targetEntity: Crm\ClienteBundle\Entity\DireccionCliente
           mappedBy: Localidad
        direcionEmpres:
           targetEntity: Crm\EmpresaBundle\Entity\DirecionEmpres
           mappedBy: Localidad
    lifecycleCallbacks: {  }
