Crm\GeneralBundle\Entity\Pais:
    type: entity
    table: null
    repositoryClass: Crm\GeneralBundle\Entity\PaisRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombrePais:
            type: string
            length: '50'
            column: nombre_pais
    oneToMany:
        estado:
             targetEntity: Crm\GeneralBundle\Entity\Estado
             mappedBy: Pais
        direccionCliente:
             targetEntity: Crm\ClienteBundle\Entity\DireccionCliente
             mappedBy: Pais
        direccionEmpresa:
             targetEntity: Crm\EmpresaBundle\Entity\DireccionEmpresa
             mappedBy: Pais
    lifecycleCallbacks: {  }
