Crm\ProductoBundle\Entity\TipoLicencia:
    type: entity
    table: null
    repositoryClass: Crm\ProductoBundle\Entity\TipoLicenciaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        precio:
            type: integer
        meses:
            type: integer
    oneToMany:
        licenciaEquipo:
          targetEntity: Crm\EquipoBundle\Entity\LicenciaEquipo
          mappedBy: TipoLicencia
    manyToOne:
        producto:
          targetEntity: Crm\ProductoBundle\Entity\Producto
          inversedBy: tipoLicencia
          joinColumn:
             name: producto_id
             referencedColumnName: id
    lifecycleCallbacks: {  }
