usuarios:
    path:     /
    defaults: { _controller: "UsuariosBundle:Usuarios:index" }

usuarios_show:
    path:     /{id}/show
    defaults: { _controller: "UsuariosBundle:Usuarios:show" }

usuarios_new:
    path:     /new
    defaults: { _controller: "UsuariosBundle:Usuarios:new" }

usuarios_create:
    path:     /create
    defaults: { _controller: "UsuariosBundle:Usuarios:create" }
    methods:  POST

usuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "UsuariosBundle:Usuarios:edit" }

usuarios_update:
    path:     /{id}/update
    defaults: { _controller: "UsuariosBundle:Usuarios:update" }
    methods:  [POST, PUT]

usuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "UsuariosBundle:Usuarios:delete" }
    methods:  [POST, DELETE]
