general_pais:
    resource: "@GeneralBundle/Resources/config/routing/pais.yml"
    prefix:   /pais

general_localidad:
    resource: "@GeneralBundle/Resources/config/routing/localidad.yml"
    prefix:   /localidad

general_estatus:
    resource: "@GeneralBundle/Resources/config/routing/estatus.yml"
    prefix:   /estatus

general_estado:
    resource: "@GeneralBundle/Resources/config/routing/estado.yml"
    prefix:   /estado

general_homepage:
    path:     /hello/{name}
    defaults: { _controller: GeneralBundle:Default:index }
