crm\licenciaBundle\Entity\Avisos:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\AvisosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUsuarios:
            type: integer
            column: id_usuarios
        aviso:
            type: text
    lifecycleCallbacks: {  }
