crm\licenciaBundle\Entity\Caracteristicas_equipo:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\Caracteristicas_equipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        versionSoftware:
            type: string
            length: '20'
            column: version_software
        numeroInterfaz:
            type: integer
            column: numero_interfaz
        dimenciones:
            type: string
            length: '20'
    manyToOne:
        procesador:
          targetEntity: crm\licenciaBundle\Entity\Procesador
          mappedBy: Caracteristicas_equipo
    manyToOne:
        capacidad:
          targetEntity: crm\licenciaBundle\Entity\Capacidad
          mappedBy: Caracteristicas_equipo
    manyToOne:
        memoria_ram:
          targetEntity: crm\licenciaBundle\Entity\Memoria_ram
          mappedBy: Caracteristicas_equipo 
    manyToOne:
        disco_duro:
          targetEntity: crm\licenciaBundle\Entity\Disco_duro
          mappedBy: Caracteristicas_equipo                             
    lifecycleCallbacks: {  }
