crm\licenciaBundle\Entity\Cliente:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\ClienteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
            column: razon_social
        rfc:
            type: string
            length: '15'
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        telExt_1:
            type: integer
            column: tel_ext_1
        telefono2:
            type: string
            length: '15'
            column: telefono_2
        telExt_2:
            type: integer
            column: tel_ext_2    
        email:
            type: string
            length: '50'
        paginaWeb:
            type: string
            length: '50'
            column: pagina_web
        fechaCreacion:
            type: datetime
            column: fecha_creacion
        fechaModificacion:
            type: datetime
            column: fecha_modificacion
        idCreacion:
            type: integer
            column: id_creacion
        idModificacion:
            type: integer
            column: id_modificacion
    manyToOne:
        estatus:
        targetEntity: crm/licenciaBundle/Entity/Estatus
        mappedBy: Cliente
    lifecycleCallbacks: {  }
