crm\licenciaBundle\Entity\Direccion_fabricante:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\Direccion_fabricanteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
        deleMuni:
            type: string
            length: '50'
            column: dele_muni
    lifecycleCallbacks: {  }
