crm\licenciaBundle\Entity\Equipo:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\EquipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numeroSerie:
            type: string
            length: '20'
            column: numero_serie
        fechaInstalacion:
            type: datetime
            column: fecha_instalacion
    manyToOne:
        procedencia:
        targetEntity: crm/licenciaBundle/Entity/Procedencia
        mappedBy: Equipo
    manyToOne:
        licencia_equipo:
        targetEntity: crm/licenciaBundle/Entity/Licencia_equipo
        mappedBy: Equipo
    manyToOne:
        cliente:
        targetEntity: crm/licenciaBundle/Entity/Cliente
        mappedBy: Equipo
    manyToOne:
        personal:
        targetEntity: crm/licenciaBundle/Entity/Personal
        mappedBy: Equipo
    manyToOne:
        venta:
        targetEntity: crm/licenciaBundle/Entity/venta
        mappedBy: Equipo
    manyToOne:
        producto:
        targetEntity: crm/licenciaBundle/Entity/Producto
        mappedBy: Equipo
    manyToOne:
        caracteristicas_equipo:
        targetEntity: crm/licenciaBundle/Entity/Caracteristicas_equipo
        mappedBy: Equipo
    manyToOne:
        estaus:
        targetEntity: crm/licenciaBundle/Entity/Estatus
        mappedBy: Equipo
    lifecycleCallbacks: {  }
