crm\licenciaBundle\Entity\Estado:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\EstadoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombreEstado:
            type: string
            length: '50'
            column: nombre_estado
    lifecycleCallbacks: {  }
