crm\licenciaBundle\Entity\Licencia_equipo:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\Licencia_equipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fechaInicio:
            type: datetime
            column: fecha_inicio
        fechaFinal:
            type: datetime
            column: fecha_final
    manyToOne:
        tipo_licencia:
        targetEntity: crm/licenciaBundle/Entity/Tipo_licencia
        mappedBy: Licencia_equipo
    lifecycleCallbacks: {  }
