crm\licenciaBundle\Entity\Modelo:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\ModeloRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '10'
    manyToOne:
        caracteristicas_equipo:
        targetEntity: crm/licenciaBundle/Entity/Caracteristicas_equipo
        mappedBy: Modelo
    lifecycleCallbacks: {  }
