crm\licenciaBundle\Entity\Personal:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\PersonalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '20'
        apePat:
            type: string
            length: '20'
            column: ape_pat
        apeMat:
            type: string
            length: '20'
            column: ape_mat
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        telefono2:
            type: string
            length: '13'
            column: telefono_2
        email:
            type: string
            length: '50'
        fechaCreacion:
            type: datetime
            column: fecha_creacion
        fechaModificacion:
            type: datetime
            column: fecha_modificacion
        idCreacion:
            type: integer
            column: id_creacion
        idModificacion:
            type: integer
            column: id_modificacion
    lifecycleCallbacks: {  }
