crm\licenciaBundle\Entity\Procedencia:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\ProcedenciaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idFabricante:
            type: integer
            column: id_fabricante
        fechaLlegada:
            type: datetime
            column: fecha_llegada
        numeroSerieFabricante:
            type: string
            length: '20'
            column: numero_serie_fabricante
        numeroSerieWarriors:
            type: string
            length: '20'
            column: numero_serie_warriors
        fechaSalida:
            type: datetime
            column: fecha_salida
    lifecycleCallbacks: {  }
