crm\licenciaBundle\Entity\Ubicacion:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\UbicacionRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idEquipo:
            type: integer
            column: id_equipo
        idEstado:
            type: integer
            column: id_estado
        idPais:
            type: integer
            column: id_pais
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
        deleMuni:
            type: string
            length: '50'
            column: dele_muni
    lifecycleCallbacks: {  }
