crm\licenciaBundle\Entity\Venta:
    type: entity
    table: null
    repositoryClass: crm\licenciaBundle\Entity\VentaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUsuarios:
            type: integer
            column: id_usuarios
        idEstatus:
            type: integer
            column: id_estatus
        idProducto:
            type: integer
            column: id_producto
        fechaVenta:
            type: datetime
            column: fecha_venta
    lifecycleCallbacks: {  }
