procedencia:
    path:     /
    defaults: { _controller: "EquipoBundle:Procedencia:index" }

procedencia_show:
    path:     /{id}/show
    defaults: { _controller: "EquipoBundle:Procedencia:show" }

procedencia_new:
    path:     /new
    defaults: { _controller: "EquipoBundle:Procedencia:new" }

procedencia_create:
    path:     /create
    defaults: { _controller: "EquipoBundle:Procedencia:create" }
    methods:  POST

procedencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "EquipoBundle:Procedencia:edit" }

procedencia_update:
    path:     /{id}/update
    defaults: { _controller: "EquipoBundle:Procedencia:update" }
    methods:  [POST, PUT]

procedencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "EquipoBundle:Procedencia:delete" }
    methods:  [POST, DELETE]
