ubicacion:
    path:     /
    defaults: { _controller: "EquipoBundle:Ubicacion:index" }

ubicacion_show:
    path:     /{id}/show
    defaults: { _controller: "EquipoBundle:Ubicacion:show" }

ubicacion_new:
    path:     /new
    defaults: { _controller: "EquipoBundle:Ubicacion:new" }

ubicacion_create:
    path:     /create
    defaults: { _controller: "EquipoBundle:Ubicacion:create" }
    methods:  POST

ubicacion_edit:
    path:     /{id}/edit
    defaults: { _controller: "EquipoBundle:Ubicacion:edit" }

ubicacion_update:
    path:     /{id}/update
    defaults: { _controller: "EquipoBundle:Ubicacion:update" }
    methods:  [POST, PUT]

ubicacion_delete:
    path:     /{id}/delete
    defaults: { _controller: "EquipoBundle:Ubicacion:delete" }
    methods:  [POST, DELETE]
