Crm\UsuariosBundle\Entity\Roles:
    type: entity
    table: null
    repositoryClass: Crm\UsuariosBundle\Entity\RolesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        roles:
            type: string
            length: '20'
    oneToMany:
        usuarios:
            targetEntity: Crm\UsuariosBundle\Entity\Usuarios
            mappedBy: Roles
    lifecycleCallbacks: {  }
