Crm\UsuariosBundle\Entity\Usuarios:
    type: entity
    table: null
    repositoryClass: Crm\UsuariosBundle\Entity\UsuariosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '20'
        contrasena:
            type: string
            length: '16'
    onyToMany:
        venta:
          targetEntity: Crm\VentasBundle\Entity\Venta 
          mappedBy: Usuarios   
        avisos:
          targetEntity: Crm\Usuarios\Entity\Avisos
    oneToOne:
        personal:
          targetEntity: Crm\PersonalBundle\Entity\Personal
          inversedBy: usuarios
          joinColumn:
              name: personal_id
              referencedColumnName: id
    manyToOne:
        rol:
          targetEntity: Crm\UsuariosBundle\Entity\Roles
          inversedBy: usuarios
          joinColumn: 
              name: rol_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
