capacidad:
    path:     /
    defaults: { _controller: "CaracteristicasBundle:Capacidad:index" }

capacidad_show:
    path:     /{id}/show
    defaults: { _controller: "CaracteristicasBundle:Capacidad:show" }

capacidad_new:
    path:     /new
    defaults: { _controller: "CaracteristicasBundle:Capacidad:new" }

capacidad_create:
    path:     /create
    defaults: { _controller: "CaracteristicasBundle:Capacidad:create" }
    methods:  POST

capacidad_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaracteristicasBundle:Capacidad:edit" }

capacidad_update:
    path:     /{id}/update
    defaults: { _controller: "CaracteristicasBundle:Capacidad:update" }
    methods:  [POST, PUT]

capacidad_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaracteristicasBundle:Capacidad:delete" }
    methods:  [POST, DELETE]
