dimenciones:
    path:     /
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:index" }

dimenciones_show:
    path:     /{id}/show
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:show" }

dimenciones_new:
    path:     /new
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:new" }

dimenciones_create:
    path:     /create
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:create" }
    methods:  POST

dimenciones_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:edit" }

dimenciones_update:
    path:     /{id}/update
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:update" }
    methods:  [POST, PUT]

dimenciones_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaracteristicasBundle:Dimenciones:delete" }
    methods:  [POST, DELETE]
