especificacionesequipo:
    path:     /
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:index" }

especificacionesequipo_show:
    path:     /{id}/show
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:show" }

especificacionesequipo_new:
    path:     /new
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:new" }

especificacionesequipo_create:
    path:     /create
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:create" }
    methods:  POST

especificacionesequipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:edit" }

especificacionesequipo_update:
    path:     /{id}/update
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:update" }
    methods:  [POST, PUT]

especificacionesequipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaracteristicasBundle:EspecificacionesEquipo:delete" }
    methods:  [POST, DELETE]
