modeloequipo:
    path:     /
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:index" }

modeloequipo_show:
    path:     /{id}/show
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:show" }

modeloequipo_new:
    path:     /new
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:new" }

modeloequipo_create:
    path:     /create
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:create" }
    methods:  POST

modeloequipo_edit:
    path:     /{id}/edit
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:edit" }

modeloequipo_update:
    path:     /{id}/update
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:update" }
    methods:  [POST, PUT]

modeloequipo_delete:
    path:     /{id}/delete
    defaults: { _controller: "CaracteristicasBundle:ModeloEquipo:delete" }
    methods:  [POST, DELETE]
