Crm\ClienteBundle\Entity\Cliente:
    type: entity
    table: null
    repositoryClass: Crm\ClienteBundle\Entity\ClienteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        razonSocial:
            type: string
            length: '50'
            column: razon_social
        rfc:
            type: string
            length: '15'
        telefono1:
            type: string
            length: '15'
            column: telefono_1
        ext1:
            type: integer
            column: ext_1
        telefono2:
            type: string
            length: '15'
            column: telefono_2
        ext2:
            type: integer
            column: ext_2
        email:
            type: string
            length: '50'
        paginaWeb:
            type: string
            length: '50'
            column: pagina_web
    manyToOne:
        estatus:
           targetEntity: Crm\GeneralBundle\Entity\Estatus
           inversedBy: cliente
           joinColumn:
                name: estatus_id
                referencedColumnName: id
    oneToMany:
        direccionCliente: 
           targetEntity: Crm\ClienteBundle\Entity\DireccionCliente
           mappedBy: Cliente
        equipo:
           targetEntity: Crm\EquipoBundle\Entity\Equipo
           mappedBy: Cliente
    lifecycleCallbacks: {  }
