Crm\ClienteBundle\Entity\DireccionCliente:
    type: entity
    table: null
    repositoryClass: Crm\ClienteBundle\Entity\DireccionClienteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
            nullable: TRUE
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
    manyToOne:
        cliente:
          targetEntity: Crm\ClienteBundle\Entity\Cliente
          inversedBy: direccionCliente
          joinColumn:
                name: cliente_id
                referencedColumnName: id
        localidad:
          targetEntity: Crm\GeneralBundle\Entity\Localidad
          inversedBy: direccionCliente
          joinColumn:
                name: localidad_id
                referencedColumnName: id
        estado:
          targetEntity: Crm\GeneralBundle\Entity\Estado
          inversedBy: direccionCliente
          joinColumn:
                name: estado_id
                referencedColumnName: id
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: direccionCliente
          joinColumn:
                name: pais_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
