Crm\EmpresaBundle\Entity\DireccionEmpresa:
    type: entity
    table: null
    repositoryClass: Crm\EmpresaBundle\Entity\DireccionEmpresaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
    manyToOne:
        empresa:
          targetEntity: Crm\EmpresaBundle\Entity\Empresa
          inversedBy: direccionEmpresa
          joinColumn:
                name: empresa_id
                referencedColumnName: id
        localidad:
          targetEntity: Crm\GeneralBundle\Entity\Localidad
          inversedBy: direccionEmpresa
          joinColumn:
                name: localidad_id
                referencedColumnName: id
        estado:
          targetEntity: Crm\GenaralBundle\Entity\Estado
          inversedBy: direccionEmpresa
          joinColumn:
                name: estado_id
                referencedColumnName: id
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          inversedBy: direccionEmpresa
          joinColumn:
                name: pais_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
