Crm\EquipoBundle\Entity\Equipo:
    type: entity
    table: null
    repositoryClass: Crm\EquipoBundle\Entity\EquipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numeroSerie:
            type: string
            length: '20'
            column: numero_serie
        fechaInstalacion:
            type: datetime
            column: fecha_instalacion
    manyToOne:
        cliente:
          targetEntity: Crm\ClienteBundle\Entity\Cliente
          inversedBy: equipo
          joinColumn:
            name: cliente_id
            referencedColumnName: id
        personal:
          targetEntity: Crm\PersonalBundle\Entity\Personal
          inversedBy: equipo
          joinColumn:
            name: personal_id
            referencedColumnName: id
        estatus:
          targetEntity: Crm\GeneralBundle\Entity\Estatus
          inversedBy: equipo
          joinColumn:
            name: estatus_id
            referencedColumnName: id
        procedencia:
          targetEntity: Crm\EquipoBundle\Entity\Procedencia
          inversedBy: equipo
          joinColumn:
            name: procedencia_id
            referencedColumnName: id
        producto:
          targetEntity: Crm\ProductoBundle\Entity\Producto
          inversedBy: equipo
          joinColumn:
            name: producto_id
            referencedColumnName: id
        especificacionesEquipo:
          targetEntity: Crm\CaracteristicasBundle\Entity\EspecificacionesEquipo
          inversedBy: equipo
          joinColumn:
            name: especificacionesEquipo_id
            referencedColumnName: id
    oneToOne:
        licenciaEquipo:
          targetEntity: Crm\EquipoBundle\Entity\LicenciaEquipo
          mappedBy: Equipo
        venta:
          targetEntity: Crm\VentaBundle\Entity\Venta
          mappedBy: Equipo
        ubicacion:
          targetEntity: Crm\EquipoBundle\Entity\Ubicacion
          mappedBy: Equipo
    lifecycleCallbacks: {  }
