usuarios_usuarios:
    resource: "@UsuariosBundle/Resources/config/routing/usuarios.yml"
    prefix:   /usuarios

usuarios_roles:
    resource: "@UsuariosBundle/Resources/config/routing/roles.yml"
    prefix:   /roles

usuarios_avisos:
    resource: "@UsuariosBundle/Resources/config/routing/avisos.yml"
    prefix:   /avisos

usuarios_homepage:
    path:     /hello/{name}
    defaults: { _controller: UsuariosBundle:Default:index }
