tipolicencia:
    path:     /
    defaults: { _controller: "ProductoBundle:TipoLicencia:index" }

tipolicencia_show:
    path:     /{id}/show
    defaults: { _controller: "ProductoBundle:TipoLicencia:show" }

tipolicencia_new:
    path:     /new
    defaults: { _controller: "ProductoBundle:TipoLicencia:new" }

tipolicencia_create:
    path:     /create
    defaults: { _controller: "ProductoBundle:TipoLicencia:create" }
    methods:  POST

tipolicencia_edit:
    path:     /{id}/edit
    defaults: { _controller: "ProductoBundle:TipoLicencia:edit" }

tipolicencia_update:
    path:     /{id}/update
    defaults: { _controller: "ProductoBundle:TipoLicencia:update" }
    methods:  [POST, PUT]

tipolicencia_delete:
    path:     /{id}/delete
    defaults: { _controller: "ProductoBundle:TipoLicencia:delete" }
    methods:  [POST, DELETE]
