Crm\CaracteristicasBundle\Entity\Capacidad:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\CapacidadRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        capacidad:
            type: integer
    oneToMany:
       especificacionesEquipo:
           targetEntity: Crm\CaracteristicasBundle\Entity\EspecificacionesEquipo
           mappedBy: Capacidad
    lifecycleCallbacks: {  }