Crm\CaracteristicasBundle\Entity\DiscoDuro:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\DiscoDuroRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marca:
            type: string
            length: '20'
        capacidad:
            type: integer
        unidad:
            type: string
            length: '10'
        tipo:
            type: string
            length: '10'
        terminoDisco:
            type: string
            length: '10'
    oneToMany:
       especificacionesEquipo:
            targetEntity: Crm\CaracteristicasBundle\Entity\EspecificacionesEquipo
            mappedBy: DiscoDuro
    lifecycleCallbacks: {  }
