Crm\CaracteristicasBundle\Entity\DiscoDuro:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\DiscoDuroRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        marca:
            type: string
            length: '20'
        capacidad:
            type: integer
        unidad:
            type: string
            length: '5'
        tipo:
            type: string
            length: '10'
        discoDuro:
            type: string
            length: '10'
    lifecycleCallbacks: {  }
