Crm\CaracteristicasBundle\Entity\EspecificacionesEquipo:
    type: entity
    table: null
    repositoryClass: Crm\CaracteristicasBundle\Entity\EspecificacionesEquipoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        numeroInterfaces:
            type: integer
            column: numero_interfaces
        numeroUsb:
            type: integer
            column: numero_usb
        expansion:
            type: boolean
    oneToMany:
        equipo:
           targetEntity: Crm\EquipoBundle\Entity\Equipo
           mappedBy: EspecificacionesEquipo
    manyToOne:
        procesador:
            targetEntity: Crm\CaracteristicasBundle\Entity\Procesador
            inversedBy: especificacionesEquipo
            joinColumn:
                name: procesador_id
                referencedColumnName: id
        capacidad:
            targetEntity: Crm\CaracteristicasBundle\Entity\Capacidad
            inversedBy: especificacionesEquipo
            joinColumn:
                name: capacidad_id
                referencedColumnName: id
        terminoMemoria:
            targetEntity: Crm\CaracteristicasBundle\Entity\MemoriaRam
            inversedBy: especificacionesEquipo
            joinColumn:
                name: memoriaRam_id
                referencedColumnName: id
        terminoDisco:
            targetEntity: Crm\CaracteristicasBundle\Entity\DiscoDuro
            inversedBy: especificacionesEquipo
            joinColumn:
                name: discoDuro_id
                referencedColumnName: id
        versionSoftware:
            targetEntity: Crm\CaracteristicasBundle\Entity\VersionSoftware
            inversedBy: especificacionesEquipo
            joinColumn:
                name: versionSoftware_id
                referencedColumnName: id
        dimenciones:
            targetEntity: Crm\CaracteristicasBundle\Entity\Dimenciones
            inversedBy: especificacionesEquipo
            joinColumn:
                name: dimenciones_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
