Crm\PersonalBundle\Entity\DireccionPersonal:
    type: entity
    table: null
    repositoryClass: Crm\PersonalBundle\Entity\DireccionPersonalRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
            nullable: true
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
    manyToOne:
        personal:
            targetEntity: Crm\PersonalBundle\Entity\Personal
            inversedBy: personal
            joinColumn:
                name: personal_id
                referencedColumnName: id
        localidad:
            targetEntity: Crm\GeneralBundle\Entity\Localidad
            inversedBy: ubicacion
            joinColumn:
                name: localidad_id
                referencedColumnName: id
        estado:
            targetEntity: Crm\GeneralBundle\Entity\Estado
            inversedBy: ubicacion
            joinColumn:
                name: estado_id
                referencedColumnName: id
        pais:
            targetEntity: Crm\GeneralBundle\Entity\Pais
            inversedBy: ubicacion
            joinColumn:
                name: pais_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
