Crm\FabricanteBundle\Entity\DireccionFabricante:
    type: entity
    table: null
    repositoryClass: Crm\FabricanteBundle\Entity\DireccionFabricanteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        calle:
            type: string
            length: '50'
        numeroExt:
            type: string
            length: '10'
            column: numero_ext
        numeroInt:
            type: string
            length: '10'
            column: numero_int
        colonia:
            type: string
            length: '50'
        codigoPostal:
            type: integer
            column: codigo_postal
    manyToOne:
        fabricante:
          targetEntity: Crm\FabricanteBundle\Entity\Fabricante
          mappedBy: DireccionFabricante
    manyToOne:
        localidad:
          targetEntity: Crm\GeneralBundle\Entity\Localidad
          mappedBy: DireccionFabricante
    manyToOne:
        estado:
          targetEntity: GeneralBundle\Entity\Estado
          mappedBy: DireccionFabricante
    manyToOne:
        pais:
          targetEntity: Crm\GeneralBundle\Entity\Pais
          mappedBy: DireccionFabricante
    lifecycleCallbacks: {  }
