Crm\VentasBundle\Entity\Venta:
    type: entity
    table: null
    repositoryClass: Crm\VentasBundle\Entity\VentaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        fechaVenta:
            type: datetime
            column: fecha_venta
    oneToMany:
       equipo:
         targetEntity: Crm\EquipoBundle\Entity\Equipo
         mappedBy: Venta
    manyToOne:
        usuarios:
          targetEntity: Crm\UsuariosBundle\Entity\Usuarios
          inversedBy: venta
          joinColumn:
              name: usuarios_id
              referencedColumnName: id
    lifecycleCallbacks: {  }